### ISSUE TITLE
App lädt nicht auf macOS

### ISSUE THREAD

**Issue by toothstone** [Richard-W/azas#1]
Von @fabianfreyer, anscheinend sind alle Browser betroffen.

Browser-Output:

> JQMIGRATE: Migrate is installed, version 1.4.1
> Error: (SystemJS) missing ) after argument list
>     SyntaxError: missing ) after argument list
>         at eval (native)
>         at F (https://zapf.pfsr.de:8444/assets/modules/systemjs/dist/system-polyfills.js:4:7484)
>         at H (https://zapf.pfsr.de:8444/assets/modules/systemjs/dist/system-polyfills.js:4:7116)
>         at q.when (https://zapf.pfsr.de:8444/assets/modules/systemjs/dist/system-polyfills.js:4:10790)
>         at b.run (https://zapf.pfsr.de:8444/assets/modules/systemjs/dist/system-polyfills.js:4:9826)
>     Evaluating https://zapf.pfsr.de:8444/assets/modules/azas/app.component.js
>     Error loading https://zapf.pfsr.de:8444/assets/modules/azas/app.component.js as "./app.component" from https://zapf.pfsr.de:8444/assets/modules/azas/main.js

**Comment by Richard-W** [comment]
Bin noch auf Arbeit. Sehe mir das heute Abend an.

**Comment by Richard-W** [comment]
Ich hab das ganze mal mit der trial-version (nur firefox leider) von einem cross-browser Cloud Dingsda angesehen und die App lädt bei mir ohne Probleme. Mit dem Test-Token konnte ich auch eine Anmeldung machen ("Dings Bums").

Ich hab dummerweise keinen Mac um das ordentlich durchzutesten. Auch Safari konnte ich nicht ausprobieren.
